"""Generate caller.cpp for a given TopK kernel function name.

The generated file wraps the NPU kernel launch in an ``extern "C"`` function
that can be called from Python via ctypes.

n_rows is passed at call time as an ``int32_t`` so the same shared library
handles any row count without recompilation.

Usage
-----
  python caller.py topk_c512_k256
  python caller.py topk_c128_k64 --block-dim 24 > caller.cpp
"""

import argparse

_DEFAULT_BLOCK_DIM = 24


def generate(fn: str, block_dim: int = _DEFAULT_BLOCK_DIM) -> str:
    return f"""\
// Auto-generated by caller.py – do not edit by hand.
#include "{fn}.cpp"

extern "C" void call_{fn}(
    void     *stream,
    uint8_t  *src,
    uint8_t  *inIdx,
    uint8_t  *out_scores,
    uint8_t  *out_indices,
    int32_t   n_rows)
{{
    {fn}<<<{block_dim}, nullptr, stream>>>(
        reinterpret_cast<float    *>(src),
        reinterpret_cast<uint32_t *>(inIdx),
        reinterpret_cast<float    *>(out_scores),
        reinterpret_cast<uint32_t *>(out_indices),
        n_rows);
}}
"""


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("fn_name", help="e.g. topk_c512_k256")
    parser.add_argument("--block-dim", type=int, default=_DEFAULT_BLOCK_DIM)
    args = parser.parse_args()
    print(generate(args.fn_name, args.block_dim), end="")
